name: Build Expo App

on:
  push:
    branches:
      - main  # Chạy khi push lên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest  # Chạy trên Linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install -g eas-cli

      - name: Authenticate with Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas login --token $EXPO_TOKEN

      - name: Configure EAS Build
        run: eas build:configure

      - name: Build APK
        run: eas build --platform android --profile preview --non-interactive